"""Structured agenda data extracted from https://devfestkochi.in/#agenda

This file was created as a best-effort parse of the site's Event Agenda
section. Some times/slots were ambiguous in the page snippets; where needed
we kept the original time strings or used best-effort mappings. Review and
adjust any times or speaker details if you need strict accuracy.

Usage:
    from agenda import AGENDA
    for item in AGENDA:
        print(item['time'], item['title'])
"""

from typing import List, Dict, Any

AGENDA: List[Dict[str, Any]] = [
    {
        "title": "Registration Starts",
        "time": "09:30 AM - 09:35 AM",
        "speaker": None,
        "role": None,
        "organization": None,
        "duration": None,
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Welcome Note",
        "time": "09:35 AM - 09:40 AM",
        "speaker": "Iqbal P B",
        "role": "Organiser",
        "organization": "GDG Cochin",
        "duration": "5 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Keynote — Artificially intelligent? No, Creative with Google AI Studio",
        "time": "09:40 AM - 10:00 AM",
        "speaker": "Merin K Jacob",
        "role": "Technical Account Manager",
        "organization": "Google",
        "duration": "20 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Keynote — Dont Call Me a Developer: Designing an AI-Accelerated Career",
        "time": "10:05 AM - 10:25 AM",
        "speaker": "Eric Hole",
        "role": "Vice President",
        "organization": "Onix",
        "duration": "20 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Sponsor Talk",
        "time": "10:30 AM - 10:40 AM",
        "speaker": "Dr. Tom M Joseph",
        "role": None,
        "organization": "Jain",
        "duration": "10 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Break",
        "time": "10:50 AM - 11:05 AM",
        "speaker": None,
        "role": None,
        "organization": None,
        "duration": "15 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Ship It Fast: AI Apps with Gemini, Firebase Studio, and $0 Infra",
        "time": "11:35 AM - 12:00 PM",
        "speaker": "Vishnu K S",
        "role": "Senior Cloud Engineer",
        "organization": "DP World",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Building Conversational Agents using ADK, A2A and MCP",
        "time": "12:05 PM - 12:30 PM",
        "speaker": "Nishi Ajmera",
        "role": "Solutions Architect",
        "organization": "Publicis Sapient (UK)",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Run SQL Everywhere: Presto Meets BigQuery and Cloud Storage",
        "time": "12:40 PM - 01:25 PM",
        "speaker": "Saurabh Mahawar",
        "role": "Developer Relations Engineer",
        "organization": "IBM",
        "duration": "45 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Lunch Break",
        "time": "12:40 PM - 01:25 PM",
        "speaker": None,
        "role": None,
        "organization": None,
        "duration": "45 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Production ready AI Agents with Security, Evaluation and Memory",
        "time": "01:25 PM - 01:50 PM",
        "speaker": "Nikhilesh Tayal",
        "role": "Google Developer Expert",
        "organization": "—",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Securing the Google Cloud: AI-Driven Threat Hunting Using Gemini",
        "time": "01:55 PM - 02:20 PM",
        "speaker": "Harisuthan S",
        "role": "Senior Security Engineer",
        "organization": "Renault Nissan Technology",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Lessons from running Go applications in Kubernetes",
        "time": "02:25 PM - 02:50 PM",
        "speaker": "Adarsh K Kumar",
        "role": "Principal Product Engineer",
        "organization": "Rapido",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Orchestrating the Modern Data Stack with Apache Airflow",
        "time": "02:55 PM - 03:20 PM",
        "speaker": "Jeevitha",
        "role": "Staff Software Engineer",
        "organization": "Juniper Networks (HP)",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Building Scalable and Ethical AI Solutions with Gemma",
        "time": "03:25 PM - 03:50 PM",
        "speaker": "Geeta Kakrani",
        "role": "Google Developer Expert",
        "organization": "AI",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Tech Talk — Securing your LLM's",
        "time": "03:55 PM - 04:20 PM",
        "speaker": "Dharmesh Vaya",
        "role": "Senior Solutions Engineer",
        "organization": "Wiz",
        "duration": "25 min",
        "location": "Main Hall",
        "notes": None,
    },
    {
        "title": "Closing Note",
        "time": "04:25 PM - 04:30 PM",
        "speaker": "Malavika",
        "role": "Organiser",
        "organization": "GDG Cochin",
        "duration": "5 min",
        "location": "Main Hall",
        "notes": None,
    },
    # Workshop / parallel track (best-effort)
    {
        "title": "Workshop — How to deploy a secure MCP server on Cloud Run?",
        "time": "02:00 AM",
        "speaker": "Ebin Babu",
        "role": "CNCF Ambassador",
        "organization": "Linux Foundation Projects",
        "duration": None,
        "location": "Workshop",
        "notes": "Parallel workshop track",
    },
]

__all__ = ["AGENDA"]
